[package]
name = "latex_renderer"
version = "0.1.0"
edition = "2021"
rust-version = "1.94"

[lib]
crate-type = ["cdylib"]

[features]
default = []
web = ["godot/experimental-wasm"]
nothreads = ["web", "godot/experimental-wasm-nothreads"]

[dependencies]
godot = { version = "0.5.2", features = ["api-4-6", "experimental-threads"] }
ratex-parser = "0.1.8"
ratex-layout = "0.1.8"
ratex-svg = { version = "0.1.8", features = ["embed-fonts"] }
ratex-katex-fonts = "0.1.8"
ratex-types = "0.1.8"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"
